server:
  port: 8761

eureka:
  instance:
    hostname: eureka.study.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    healthcheck:
#      enable: true
#  server:
#    enable-self-preservation: false
