eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: admin
logging:
  level:
    root: INFO
management:
  security:
    enabled: false