server:
  port: 8000

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-gw

#logging:
#  level:
#    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

zuul:
  prefix: /api
  stripPrefix: true
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  ignoredServices: '*'
  routes:
    alpha:
      path: /a/**
      serviceId: alpha
      stripPrefix: false
    bravo:
      path: /b/**
      serviceId: bravo
      stripPrefix: false

ribbon:
  ReadTimeout: 8000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0
  retryableStatusCodes: 500,503
  OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      execution:
        isolation:
#          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
        timeout:
          enabled: true
#  threadpool:
#    default:
#      coreSize: 10
#      maxQueueSize: 100
#      queueSizeRejectionThreshold: 100
#    sleepy:
#      maxQueueSize: 10
#      queueSizeRejectionThreshold: 10


