server:
  port: 8101

spring:
  application:
    name: zuul-gw
  datasource:
    url: jdbc:h2:~/apig;AUTO_SERVER=TRUE
    username: apig
    password: apig

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka.study.com:8761/eureka/

#logging:
#  level:
#    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

zuul:
  ignoredServices: '*'
#  routes:
#    default:
#      path: /**
  servlet-path: /

ribbon:
  ReadTimeout: 8000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0
  retryableStatusCodes: 500,503
  OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      execution:
        isolation:
#          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
        timeout:
          enabled: true
#  threadpool:
#    default:
#      coreSize: 10
#      maxQueueSize: 100
#      queueSizeRejectionThreshold: 100
#    sleepy:
#      maxQueueSize: 10
#      queueSizeRejectionThreshold: 10


