server:
  port: 8081
#  maxHttpHeaderSize: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

## 同时用于 service id （除非用 eureka.instance.appname 特别指定）
spring:
  application:
    name: alpha

#logging:
#  level:
#    root: INFO

## Actuator
# 加载所有的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always

## Hystrix
# 设置默认超时（超时就会走 fallback 方法，同时会 Interrupt 当前线程），默认1秒
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000
            interruptOnTimeout : true
        timeout:
          enabled: true
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 100
      queueSizeRejectionThreshold: 100
    sleepy:
      maxQueueSize: 10
      queueSizeRejectionThreshold: 10


